### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by christoph-morrison** [bessarabov/mac2mqtt#10]
Hallo Ivan,

is it possible that you release your code with under an open source license?

Yours
Christoph

**Comment by bessarabov** [comment]
@christoph-morrison you are absolutely right, thank you! This is my mistake that I didn't specified the licence from the very beginning.

Done In commit https://github.com/bessarabov/mac2mqtt/commit/2f14d56879df44cfa2c6c2423602b0b94d1ba26a — I have added MIT LICENSE

I'm closing this issues.

**Comment by christoph-morrison** [comment]
Much appreciated.
